version = 1


[install]
hello.pkg-path = "hello"
cowsay.pkg-path = "cowsay"
bash.pkg-path = "bash"

[vars]
INTRO_MESSAGE = "It's gettin' Flox in here"

[hook]
on-activate = '''
echo "Hello from Flox! on-activate"
'''

[profile]
common = '''
echo "Hello from Flox! profile"
'''

